services:
  geoserver:
    image: kartoza/geoserver:2.23.2
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./geoserver/data_dir:/var/lib/geoserver/data_dir

  database:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      - POSTGRES_DB=geoserver_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
